### ISSUE TITLE
不支持composer安装？

### ISSUE THREAD

**Issue by fastgoo** [swoole/grpc-client#2]

**Comment by Declarcall** [comment]
https://packagist.org/?query=swoole%2Fetcd-client
No packages found.
应该是没开发完吧

**Comment by twose** [comment]
@EDDYCJY 稍后发个正式版

**Comment by marscoo** [comment]
貌似還沒上packagist，這裡給個懶人包：

在composer.json的repositories暫時加入此段

```
    "repositories": [
      {
        "url": "https://github.com/swoole/grpc-client.git",
        "type": "git"
      }
    ],
```

再執行一次`composer require swoole/grpc-client`即可
