### ISSUE TITLE
关于 grpc/greeter_server.php 的一些疑问

### ISSUE THREAD

**Issue by EDDYCJY** [swoole/grpc-client#3]
@twose 又来打扰您了，我看了 grpc/greeter_server.php， 有了以下的疑问想要请教您 🤔

--

在示例代码中，是直接指定 `SayHello` 的 `HelloRequest` 和 `HelloReply` 去响应的。而在真实的案例中，一个 server 端，是会承载多个 service，也就承载着对应的多个 rpc 接口

是需要判断对应是来自哪个 service，哪个 rpc 接口方法。像 Go 的 gRPC Server 的话，是会将其注册到内部的服务管理中，然后进行各种内部服务发现判断

那么这个 demo 显然就无法处理，想请问 twose 对此有没有什么好的实现方案或建议？

莫非是在 `swoole_http_request $request` 中能够取到对应的 service 和 rpc 方法接口名称，然后做映射吗？

```
$http->on('request', function (swoole_http_request $request, swoole_http_response $response) use ($http) {
    /**@var $request_message HelloRequest */
    $request_message = Grpc\Parser::deserializeMessage([HelloRequest::class, null], $request->rawcontent());
    if ($request_message) {
        $response_message = new HelloReply();
        $response_message->setMessage('Hello ' . $request_message->getName());
        $response->header('content-type', 'application/grpc');
        $response->header('trailer','grpc-status, grpc-message');
        $trailer = [
            "grpc-status" => "0",
            "grpc-message" => ""
        ];
        foreach ($trailer as $trailer_name => $trailer_value) {
            $response->trailer($trailer_name, $trailer_value);
        }
        $response->end(Grpc\Parser::serializeMessage($response_message));
    } else {
        $response->end('failed');
    }
});
```

感谢！

**Comment by twose** [comment]
所以说是要做路由的, 你可以看下etcd的源码, 比如说
https://github.com/swoole/grpc-client/blob/master/src/Etcd/Etcdserverpb/KVClient.php
```php
    /**
     * Range gets the keys in the range from the key-value store.
     * @param \Etcdserverpb\RangeRequest $argument input argument
     * @param array $metadata metadata
     * @param array $options call options
     * @return \Etcdserverpb\RangeResponse[]|\Grpc\StringifyAble[]
     */
    public function Range(\Etcdserverpb\RangeRequest $argument,
      $metadata = [], $options = []) {
        return $this->_simpleRequest('/etcdserverpb.KV/Range',
        $argument,
        ['\Etcdserverpb\RangeResponse', 'decode'],
        $metadata, $options);
    }
```
其实这个请求对应的uri就是 `http://127.0.0.1/etcdserverpb.KV/Range`
PHP还没有现成的server端生态, 而路由最好是和开发者选定的开发框架一起实现的

**Comment by EDDYCJY** [comment]
好的 我仔细研究研究，感谢 @twose

**Comment by EDDYCJY** [comment]
@twose 您好 twose，我发现在 grpc/greeter_server.php 中的 

```
$http->on('request', function (swoole_http_request $request, swoole_http_response $response) use ($http) {}
```

在 grpc_client.php 请求 server 端的时候（非流式），是会触发 2 次事件的，分别是：

- 客户端的请求
- 客户端的关闭（Close）

虽然在非流式中，request_method  都是 POST，但是流式不一定吧。那  request_method 不能用来做判断依据

就算设置了 `$http->on('close', ...)` 也会在 `$http->on('request'...)` 触发 Close 事件...

--

想请问 twose，Swoole 在这块有什么好的处理方法吗？还是硬判断 request_uri 为 `>>>SWOOLE|CLOSE<<<` 则跳过处理？

**Comment by twose** [comment]
那个是针对协程挂起状态不可强行中断的特殊处理, 只需要服务端路由忽略错误的路径给出类似404响应就可以, 这个请求没有实际意义, 只是为了通过IO事件通知接收数据的协程退出.
你可以使用closeWait, 等待所有请求处理完毕自动关闭接收的协程, 而不是通过这个强制close.

**Comment by EDDYCJY** [comment]
@twose 了解，我现在先通过对比 
```
if ($request->server['request_uri']) == Grpc\Client::CLOSE_KEYWORD) ...
```
 来 ban 掉它了
