### ISSUE TITLE
It doesn't work in swoole v4.3.2

### ISSUE THREAD

**Issue by woody712** [swoole/grpc-client#7]
I used this client in v4.2.9, everything is OK.

And I updated swoole to v4.3.2, the client can not work.

`
$kvClient = new \Etcdserverpb\KVClient($host);

$kvClient->start();

$rangeRequest = new \Etcdserverpb\RangeRequest();

$rangeRequest->setKey('key');

$rangeRequest->setRangeEnd($this->addOneBit('key'));

$results = $kvClient->Range($rangeRequest);

$rangeResponse = $results[0];
`
there is no respone.

**Comment by twose** [comment]
We found a serious bug (http2 client) in this version (v4.3.2), please roll back the version first, we will fix in v.4.3.3.

**Comment by twose** [comment]
https://github.com/swoole/swoole-src/releases/tag/v4.3.3
